name: Server Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "node"
                  cache: "npm"
            - name: Install dependencies
              run: npm install
              working-directory: server
            - name: Run tests
              run: npm run test
              working-directory: server
